server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    external_labels:
      host: ${HOSTNAME}

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
      - source_labels: ['container']
        target_label: service
        replacement: other
      - source_labels: ['container']
        regex: marconi-backend
        target_label: service
        replacement: backend
      - source_labels: ['container']
        regex: marconi-worker
        target_label: service
        replacement: worker
      - source_labels: ['container']
        regex: marconi-deadline-poller
        target_label: service
        replacement: deadline_poller
      - source_labels: ['container']
        regex: marconi-jobe
        target_label: service
        replacement: jobe
      - source_labels: ['container']
        regex: .*nginx.*|.*proxy.*
        target_label: service
        replacement: nginx

    pipeline_stages:
      - docker: {}
